### ISSUE TITLE
Ask the security questions when the user first logs in rather than when the user is checking account info

### ISSUE THREAD

**Issue by ghost** [lilhumza/Bank#10]
Makes more sense. @alk0rani

**Comment by alk0rani** [comment]
In actual banks and other services, the security questions are asked when very important information needs to be disclosed. Hence, it is asked when the user wants to access their account information. Perhaps I can adjust it so that it asks the security questions if the user wants to access the bankTeller. Otherwise, it actually makes more sense like this. @Draftyshark

**Comment by ghost** [comment]
So it’s ok to withdraw money/ view bank inquiries without answering security question?

**Comment by alk0rani** [comment]
Yeah. In real life, you wouldn't need to security questions to withdraw money. Rather, you would need your accountNumber and PIN (for verification). On the other hand, I would see why some bank inquiries would need security questions such as closing an account or changing transaction history. This is why I thought it would make sense to ask the user their security questions when going to the bank teller. @Draftyshark

**Comment by ghost** [comment]
K
